on:
  poll:
    url: ${{ secrets.API2 }}
    requestConfig:
      method: GET
      headers:
        Authorization: Bearer ${{ secrets.API2_TOKEN }}
    itemsPath: items
    deduplicationKey: _id
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        run: echo "link:${{ on.poll.outputs.link }}"
      - name: Make a HTTP Request      
        uses: actionsflow/axios@main
        with:
          url: https://cubox.pro/c/api/save/${{ secrets.API_TOKEN }}
          accept: 200
          timeout: 10000
          method: POST
          body: |
            {
              "content":"${{ on.poll.outputs.link }}", 
              "type":"url",
              "folder":"Library"
            }
